set_property PACKAGE_PIN P17 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100M]
set_property PACKAGE_PIN V7 [get_ports dac_xfer_n]
set_property PACKAGE_PIN U7 [get_ports {sine[5]}]
set_property PACKAGE_PIN T8 [get_ports {sine[0]}]
set_property PACKAGE_PIN N6 [get_ports dac_cs_n]
set_property PACKAGE_PIN V6 [get_ports dac_wr1_n]
set_property PACKAGE_PIN R6 [get_ports dac_wr2_n]
set_property PACKAGE_PIN R5 [get_ports dac_ile]
set_property PACKAGE_PIN U9 [get_ports {sine[7]}]
set_property PACKAGE_PIN V9 [get_ports {sine[6]}]
set_property PACKAGE_PIN U6 [get_ports {sine[4]}]
set_property PACKAGE_PIN R7 [get_ports {sine[3]}]
set_property PACKAGE_PIN T6 [get_ports {sine[2]}]
set_property PACKAGE_PIN R8 [get_ports {sine[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sine[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sine[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sine[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sine[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sine[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sine[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sine[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sine[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports dac_ile]
set_property IOSTANDARD LVCMOS33 [get_ports dac_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports dac_wr1_n]
set_property IOSTANDARD LVCMOS33 [get_ports dac_wr2_n]
set_property IOSTANDARD LVCMOS33 [get_ports dac_xfer_n]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk/inst/clk_in1_clk_wiz_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dds_inst/m_axis_data_tdata[0]} {dds_inst/m_axis_data_tdata[1]} {dds_inst/m_axis_data_tdata[2]} {dds_inst/m_axis_data_tdata[3]} {dds_inst/m_axis_data_tdata[4]} {dds_inst/m_axis_data_tdata[5]} {dds_inst/m_axis_data_tdata[6]} {dds_inst/m_axis_data_tdata[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_ila]
