set_property SRC_FILE_INFO {cfile:H:/workSpace/xilinx/D7C/prj5_MicroBlaze/prj5_MicroBlaze.srcs/constrs_1/new/con_prj5.xdc rfile:../../../prj5_MicroBlaze.srcs/constrs_1/new/con_prj5.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports clk_in1_0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports uart_rtl_0_txd]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports uart_rtl_0_rxd]
