set_property PACKAGE_PIN P17 [get_ports clk_in1_0]
set_property PACKAGE_PIN T4 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN N5 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
